### ISSUE TITLE
Adding Hashtags / pics

### ISSUE THREAD

**Issue by johnpatkinson** [dasdom/Poster#8] opened 2015-07-09 07:00 UTC
Dominik
When adding hashtags it automatically adds a space between the hashtag and the wording. 
![poster](https://cloud.githubusercontent.com/assets/5547278/8589642/69d6fa34-2610-11e5-9eac-399ae312c35c.jpg)
Also when adding a picture it makes it square as in Instagram square will this be fixed in the future as this is the first app i have seen do this.

**Comment by dasdom** [comment] 2015-07-09 07:06
Thanks! I'll fix both hopefully this weekend.

**Comment by johnpatkinson** [comment] 2015-07-09 07:58
Thanks Dominik :)

**Comment by dasdom** [comment] 2015-07-09 20:27
Could you please check again the hashtag issue? Because I can't reproduce it.

**Comment by dasdom** [comment] 2015-07-10 08:17
Should be fixed in version 0.4

**Closed as completed** 2015-07-10 08:17 UTC
